// flow-typed signature: 78b82b41e6d323702e6f3716c030c5d1
// flow-typed version: <<STUB>>/redux-persist-migrate_v^4.1.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-persist-migrate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-persist-migrate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-persist-migrate/lib/index' {
  declare module.exports: any;
}

declare module 'redux-persist-migrate/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-persist-migrate/lib/index.js' {
  declare module.exports: $Exports<'redux-persist-migrate/lib/index'>;
}
declare module 'redux-persist-migrate/src/index.js' {
  declare module.exports: $Exports<'redux-persist-migrate/src/index'>;
}
